obj-$(CONFIG_AMLOGIC_MEDIA_VENC_VCENC)	+= vc8000.o
vc8000-objs +=  vc8000_driver.o
vc8000-objs +=  vc8000_vcmd_driver.o
vc8000-objs +=  bidirect_list.o
vc8000-objs +=  vcmdswhwregisters.o
vc8000-objs +=  vc8000_normal_driver.o