#ifndef PTS_SERVER_DEV_HEAD_HH
#define PTS_SERVER_DEV_HEAD_HH

#define PTSSERVER_IOC_MAGIC 'P'
#define PTSSERVER_IOC_INSTANCE_ALLOC _IOW(PTSSERVER_IOC_MAGIC, 0x01, int)
#define PTSSERVER_IOC_INSTANCE_GET   _IOW(PTSSERVER_IOC_MAGIC, 0x02, int)
#define PTSSERVER_IOC_CHECKIN_PTS   _IOW(PTSSERVER_IOC_MAGIC, 0x03, int)
#define PTSSERVER_IOC_CHECKOUT_PTS   _IOW(PTSSERVER_IOC_MAGIC, 0x04, int)
#define PTSSERVER_IOC_PEEK_PTS   _IOW(PTSSERVER_IOC_MAGIC, 0x05, int)
#define PTSSERVER_IOC_SET_ALIGNMENT_OFFSET   _IOW(PTSSERVER_IOC_MAGIC, 0x06, int)
#define PTSSERVER_IOC_GET_LAST_CHECKIN_PTS   _IOW(PTSSERVER_IOC_MAGIC, 0x07, int)
#define PTSSERVER_IOC_GET_LAST_CHECKOUT_PTS   _IOW(PTSSERVER_IOC_MAGIC, 0x08, int)
#define PTSSERVER_IOC_RELEASE   _IOW(PTSSERVER_IOC_MAGIC, 0x09, int)

#endif

